# Generated by Django 5.2.4 on 2025-07-31 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('lux', 'Люкс'), ('std', 'Стандарт'), ('eco', 'Економ')], max_length=50)),
                ('amount_of_beds', models.IntegerField(default=1)),
                ('max_guests', models.IntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='room_pictures/')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('email', models.EmailField(default='noname@example.com', max_length=254)),
                ('status', models.CharField(choices=[('wtn', 'Очікує підтвердження'), ('cnf', 'Підтверджено'), ('clc', 'Скасовано')], default='wtn', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.room')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-created_at'],
            },
        ),
    ]
