# Generated by Django 5.2.4 on 2025-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='is_available',
        ),
        migrations.AddField(
            model_name='rooms',
            name='amount_of_beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='room_pictures/'),
        ),
    ]
