# Generated by Django 5.2.4 on 2025-07-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_remove_rooms_is_available_rooms_amount_of_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('lux', 'Люкс'), ('std', 'Стандарт'), ('eco', 'Економ')], max_length=50)),
                ('amount_of_beds', models.IntegerField(default=1)),
                ('max_guests', models.IntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='room_pictures/')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
                'ordering': ['room_number'],
            },
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.room'),
        ),
    ]
