# Generated by Django 5.2.4 on 2025-07-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_room_rename_users_user_delete_rooms_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
