# Generated by Django 5.2.4 on 2025-07-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_rename_booking_bookings_rename_room_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
